[2023-07-10 14:10:47,273] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:50,506] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:50] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:50,552] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:50] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:50,563] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:50] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:50,566] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:50] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:51,051] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:51] "[33mGET /openapi/static/js/swagger-ui-bundle.js.map HTTP/1.1[0m" 404 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:51,119] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:51] "[33mGET /openapi/static/css/swagger-ui.css.map HTTP/1.1[0m" 404 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:51,257] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:51] "[33mGET /openapi/static/js/swagger-ui-standalone-preset.js.map HTTP/1.1[0m" 404 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:51,391] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:51] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:10:51,439] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:10:51] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:11:03,561] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Marcos Filipi' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:11:03,565] WARNING add_paciente() L54   Erro ao adicionar paciente 'Marcos Filipi', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:11:03,566] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:11:03] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:11:05,702] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Marcos Filipi' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:11:05,703] WARNING add_paciente() L54   Erro ao adicionar paciente 'Marcos Filipi', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:11:05,704] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:11:05] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:11:16,501] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:11:16,504] DEBUG get_pacientes() L81   1 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:11:16,504] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:11:16] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:12:01,970] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Ana' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:12:01,972] WARNING add_paciente() L54   Erro ao adicionar paciente 'Ana', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:12:01,973] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:12:01] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:12:03,598] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Ana' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:12:03,599] WARNING add_paciente() L54   Erro ao adicionar paciente 'Ana', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:12:03,599] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:12:03] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:12:11,404] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:12:11,405] DEBUG get_pacientes() L81   1 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:12:11,406] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:12:11] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:12:29,243] DEBUG add_paciente() L40   Adicionando paciente de nome: 'ana' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:12:29,255] DEBUG add_paciente() L48   Adicionado paciente de nome: 'ana' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L48  
[2023-07-10 14:12:29,258] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:12:29] "POST /paciente HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:13:01,503] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:13:01,505] DEBUG get_pacientes() L81   2 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:13:01,506] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:13:01] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:13:27,942] DEBUG add_paciente() L40   Adicionando paciente de nome: 'jose' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:13:27,953] DEBUG add_paciente() L48   Adicionado paciente de nome: 'jose' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L48  
[2023-07-10 14:13:27,954] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:13:27] "POST /paciente HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:13:33,942] DEBUG add_paciente() L40   Adicionando paciente de nome: 'jose' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:13:33,943] WARNING add_paciente() L54   Erro ao adicionar paciente 'jose', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:13:33,943] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:13:33] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:13:44,597] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:13:44,603] DEBUG get_pacientes() L81   3 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:13:44,603] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:13:44] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:17:47,310] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
