[2023-07-10 15:06:52,740] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:06:52] "POST /paciente HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:07:14,125] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 15:07:14,127] DEBUG get_pacientes() L81   2 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 15:07:14,127] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:07:14] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:07:43,408] DEBUG add_comentario() L145  Adicionando coment√°rios ao paciente #1 - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L145 
[2023-07-10 15:07:43,410] WARNING add_comentario() L154  Erro ao adicionar coment√°rio ao paciente '1', Paciente n√£o encontrado na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L154 
[2023-07-10 15:07:43,410] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:07:43] "[33mPOST /cometario HTTP/1.1[0m" 404 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:07:49,064] DEBUG add_comentario() L145  Adicionando coment√°rios ao paciente #3 - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L145 
[2023-07-10 15:07:49,074] DEBUG add_comentario() L165  Adicionado coment√°rio ao paciente #3 - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L165 
[2023-07-10 15:07:49,076] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:07:49] "POST /cometario HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:08:22,475] DEBUG get_paciente() L94   Coletando dados sobre o paciente #Ana - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L94  
[2023-07-10 15:08:22,476] WARNING get_paciente() L103  Erro ao buscar o paciente 'Ana', Paciente n√£o encontrado na base de dados:/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L103 
[2023-07-10 15:08:22,476] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:08:22] "[33mGET /paciente?nome=Ana HTTP/1.1[0m" 404 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:08:52,659] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
